version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.11.1-browsers

        environment:
            BS_PROJECT: "hirst-dialog on CircleCI"

        steps:
            - checkout
            - run:
                name: Change npm-global directory
                command: |
                    npm config set prefix ~/.npm-global
                    echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
            - run:
                name: Update WebDriver
                command: |
                    sudo apt-get remove firefox-mozilla-build binutils &&
                    sudo sh -c "echo 'deb http://ftp.hr.debian.org/debian sid main' >> /etc/apt/sources.list" &&
                    sudo apt-get update &&
                    sudo apt-get install -t sid firefox &&
                    firefox --version
            - run:
                name: Prerequisites
                command: |
                    npm i -g polymer-cli --unsafe-perm
                    npm i -g bower
            - run:
                name: Install components
                command: |
                    npm config get prefix
                    npm ls --depth=0 --global
                    bower install
            - run:
                name: Run tests
                command: polymer test
