version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.11.1-browsers

        environment:
            BS_PROJECT: "hirst-dialog on CircleCI"

        steps:
            - checkout
            - run:
                name: Prerequisites
                command: |
                    npm config set prefix ~/.npm-global
                    npm i -g polymer-cli --unsafe-perm
                    npm i -g bower
            - run:
                name: Install components
                command: |
                    npm config get prefix
                    npm ls --depth=0 --global
                    bower install
            - run:
                name: Run tests
                command: polymer test
